name: grupotdl
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  intl: ^0.20.2
  uuid: ^4.0.0
  sqflite: ^2.3.2
  path: ^1.8.3
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  phosphor_flutter: ^2.0.0
  flutter_multi_formatter: ^2.5.0
  board_datetime_picker: 2.5.0
  table_calendar: ^3.0.9
  fl_chart: ^0.63.0
  logging: ^1.2.0
  retry: ^3.1.0
  image_picker: ^1.0.4
  collection: ^1.18.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  intl_utils: ^2.8.7 
  mockito: ^5.4.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/logo2.png
    - assets/tdl.png
    - assets/giftcard.jpg
    - assets/giftcard.jpeg
    - assets/testAgenda.png

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated

